name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - master
      - rocm-*
    paths-ignore:
      - "docs/**"

# only run the latest commit to avoid cache overwrites
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.11

jobs:
  amd64_build:
    runs-on: ubuntu-22.04
    name: AMD64 Build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/main/Dockerfile
          push: false
          platforms: linux/amd64
          target: frigate
          tags: ${{ steps.setup.outputs.image-name }}-amd64
          cache-from: type=registry,ref=${{ steps.setup.outputs.cache-name }}-amd64
          cache-to: type=registry,ref=${{ steps.setup.outputs.cache-name }}-amd64,mode=max
  
  amd64_extra_builds:
    runs-on: ubuntu-22.04
    name: AMD64 ROCm Build
    needs:
      - amd64_build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        env:
          HSA_OVERRIDE: 0
        uses: docker/bake-action@v7
        with:
          source: .
          push: true
          targets: rocm
          files: docker/rocm/rocm.hcl
          set: |
            rocm.tags=${{ steps.setup.outputs.image-name }}-${{ github.ref_name }}
            rocm.tags=${{ steps.setup.outputs.latest-name }}-${{ github.ref_name }}
            *.cache-to=type=registry,ref=${{ steps.setup.outputs.cache-name }}-rocm,mode=max
            *.cache-from=type=registry,ref=${{ steps.setup.outputs.cache-name }}-rocm
